# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools

default_platform(:ios)

platform :ios do

  # -----------------------
  # lanes
  # -----------------------
  lane :tests do
    spm(
      command: "test",
      configuration: "debug",
      enable_code_coverage: true,
      xcpretty_output: "simple",
      build_path: "./build"
    )
  end

  lane :build do
    tests
  end
end