name: build
on:
  pull_request:
  push:
    branches:
      - 'main'
jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - run: bundle install; bundle exec fastlane build